### ISSUE TITLE
.env file

### ISSUE THREAD

**Issue by jirevwe** [allengblack/MockPremierLeague#2]
Hi @allengblack,

Please provide a sample .env file you used. You can paste it here.

**Comment by allengblack** [comment]
PORT=3000
SECRET_KEY=R*WCyIBE^REwY27eDT&wV20XRkI(kuRH^uLzMvLk
DB_USERNAME=root
DB_PASSWORD=admin
DB_DATABASE=mockpremierleague
DB_HOST=127.0.0.1
DB_DIALECT=mysql
NODE_ENV=development
